# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
