# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0006_rate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='rates',
        ),
        migrations.AddField(
            model_name='rate',
            name='poem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poems.Poem'),
            preserve_default=False,
        ),
    ]
